# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '2048.ui'
#
# Created by: PyQt5 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(600, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.background = QtWidgets.QWidget(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, -20, 600, 600))
        self.background.setStyleSheet(_fromUtf8("background-color:#ffffff;"))
        self.background.setObjectName(_fromUtf8("background"))
        self.widget = QtWidgets.QWidget(self.background)
        self.widget.setGeometry(QtCore.QRect(75, 130, 450, 450))
        self.widget.setStyleSheet(_fromUtf8("background-color:#cacaca;"))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.case0x0 = QtWidgets.QLabel(self.widget)
        self.case0x0.setGeometry(QtCore.QRect(10, 10, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.case0x0.setFont(font)
        self.case0x0.setStyleSheet(_fromUtf8("background-color:#ffffde;"))
        self.case0x0.setText(_fromUtf8(""))
        self.case0x0.setTextFormat(QtCore.Qt.AutoText)
        self.case0x0.setAlignment(QtCore.Qt.AlignCenter)
        self.case0x0.setWordWrap(False)
        self.case0x0.setObjectName(_fromUtf8("case0x0"))
        self.case0x0_2 = QtWidgets.QLabel(self.widget)
        self.case0x0_2.setGeometry(QtCore.QRect(120, 10, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.case0x0_2.setFont(font)
        self.case0x0_2.setStyleSheet(_fromUtf8("background-color:#ffffde;"))
        self.case0x0_2.setText(_fromUtf8(""))
        self.case0x0_2.setTextFormat(QtCore.Qt.AutoText)
        self.case0x0_2.setAlignment(QtCore.Qt.AlignCenter)
        self.case0x0_2.setWordWrap(False)
        self.case0x0_2.setObjectName(_fromUtf8("case0x0_2"))
        self.case0x0_3 = QtWidgets.QLabel(self.widget)
        self.case0x0_3.setGeometry(QtCore.QRect(230, 10, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.case0x0_3.setFont(font)
        self.case0x0_3.setStyleSheet(_fromUtf8("background-color:#ffffde;"))
        self.case0x0_3.setText(_fromUtf8(""))
        self.case0x0_3.setTextFormat(QtCore.Qt.AutoText)
        self.case0x0_3.setAlignment(QtCore.Qt.AlignCenter)
        self.case0x0_3.setWordWrap(False)
        self.case0x0_3.setObjectName(_fromUtf8("case0x0_3"))
        self.case0x0_4 = QtWidgets.QLabel(self.widget)
        self.case0x0_4.setGeometry(QtCore.QRect(340, 10, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.case0x0_4.setFont(font)
        self.case0x0_4.setStyleSheet(_fromUtf8("background-color:#ffffde;"))
        self.case0x0_4.setText(_fromUtf8(""))
        self.case0x0_4.setTextFormat(QtCore.Qt.AutoText)
        self.case0x0_4.setAlignment(QtCore.Qt.AlignCenter)
        self.case0x0_4.setWordWrap(False)
        self.case0x0_4.setObjectName(_fromUtf8("case0x0_4"))
        self.case0x0_5 = QtWidgets.QLabel(self.widget)
        self.case0x0_5.setGeometry(QtCore.QRect(10, 120, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.case0x0_5.setFont(font)
        self.case0x0_5.setStyleSheet(_fromUtf8("background-color:#ffffde;"))
        self.case0x0_5.setText(_fromUtf8(""))
        self.case0x0_5.setTextFormat(QtCore.Qt.AutoText)
        self.case0x0_5.setAlignment(QtCore.Qt.AlignCenter)
        self.case0x0_5.setWordWrap(False)
        self.case0x0_5.setObjectName(_fromUtf8("case0x0_5"))
        self.case0x0_6 = QtWidgets.QLabel(self.widget)
        self.case0x0_6.setGeometry(QtCore.QRect(120, 120, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.case0x0_6.setFont(font)
        self.case0x0_6.setStyleSheet(_fromUtf8("background-color:#ffffde;"))
        self.case0x0_6.setText(_fromUtf8(""))
        self.case0x0_6.setTextFormat(QtCore.Qt.AutoText)
        self.case0x0_6.setAlignment(QtCore.Qt.AlignCenter)
        self.case0x0_6.setWordWrap(False)
        self.case0x0_6.setObjectName(_fromUtf8("case0x0_6"))
        self.case0x0_7 = QtWidgets.QLabel(self.widget)
        self.case0x0_7.setGeometry(QtCore.QRect(230, 120, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.case0x0_7.setFont(font)
        self.case0x0_7.setStyleSheet(_fromUtf8("background-color:#ffffde;"))
        self.case0x0_7.setText(_fromUtf8(""))
        self.case0x0_7.setTextFormat(QtCore.Qt.AutoText)
        self.case0x0_7.setAlignment(QtCore.Qt.AlignCenter)
        self.case0x0_7.setWordWrap(False)
        self.case0x0_7.setObjectName(_fromUtf8("case0x0_7"))
        self.case0x0_8 = QtWidgets.QLabel(self.widget)
        self.case0x0_8.setGeometry(QtCore.QRect(340, 120, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.case0x0_8.setFont(font)
        self.case0x0_8.setStyleSheet(_fromUtf8("background-color:#ffffde;"))
        self.case0x0_8.setText(_fromUtf8(""))
        self.case0x0_8.setTextFormat(QtCore.Qt.AutoText)
        self.case0x0_8.setAlignment(QtCore.Qt.AlignCenter)
        self.case0x0_8.setWordWrap(False)
        self.case0x0_8.setObjectName(_fromUtf8("case0x0_8"))
        self.case0x0_9 = QtWidgets.QLabel(self.widget)
        self.case0x0_9.setGeometry(QtCore.QRect(10, 230, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.case0x0_9.setFont(font)
        self.case0x0_9.setStyleSheet(_fromUtf8("background-color:#ffffde;"))
        self.case0x0_9.setText(_fromUtf8(""))
        self.case0x0_9.setTextFormat(QtCore.Qt.AutoText)
        self.case0x0_9.setAlignment(QtCore.Qt.AlignCenter)
        self.case0x0_9.setWordWrap(False)
        self.case0x0_9.setObjectName(_fromUtf8("case0x0_9"))
        self.case0x0_10 = QtWidgets.QLabel(self.widget)
        self.case0x0_10.setGeometry(QtCore.QRect(120, 230, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.case0x0_10.setFont(font)
        self.case0x0_10.setStyleSheet(_fromUtf8("background-color:#ffffde;"))
        self.case0x0_10.setText(_fromUtf8(""))
        self.case0x0_10.setTextFormat(QtCore.Qt.AutoText)
        self.case0x0_10.setAlignment(QtCore.Qt.AlignCenter)
        self.case0x0_10.setWordWrap(False)
        self.case0x0_10.setObjectName(_fromUtf8("case0x0_10"))
        self.case0x0_11 = QtWidgets.QLabel(self.widget)
        self.case0x0_11.setGeometry(QtCore.QRect(230, 230, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.case0x0_11.setFont(font)
        self.case0x0_11.setStyleSheet(_fromUtf8("background-color:#ffffde;"))
        self.case0x0_11.setText(_fromUtf8(""))
        self.case0x0_11.setTextFormat(QtCore.Qt.AutoText)
        self.case0x0_11.setAlignment(QtCore.Qt.AlignCenter)
        self.case0x0_11.setWordWrap(False)
        self.case0x0_11.setObjectName(_fromUtf8("case0x0_11"))
        self.case0x0_12 = QtWidgets.QLabel(self.widget)
        self.case0x0_12.setGeometry(QtCore.QRect(340, 230, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.case0x0_12.setFont(font)
        self.case0x0_12.setStyleSheet(_fromUtf8("background-color:#ffffde;"))
        self.case0x0_12.setText(_fromUtf8(""))
        self.case0x0_12.setTextFormat(QtCore.Qt.AutoText)
        self.case0x0_12.setAlignment(QtCore.Qt.AlignCenter)
        self.case0x0_12.setWordWrap(False)
        self.case0x0_12.setObjectName(_fromUtf8("case0x0_12"))
        self.case0x0_13 = QtWidgets.QLabel(self.widget)
        self.case0x0_13.setGeometry(QtCore.QRect(10, 340, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.case0x0_13.setFont(font)
        self.case0x0_13.setStyleSheet(_fromUtf8("background-color:#ffffde;"))
        self.case0x0_13.setText(_fromUtf8(""))
        self.case0x0_13.setTextFormat(QtCore.Qt.AutoText)
        self.case0x0_13.setAlignment(QtCore.Qt.AlignCenter)
        self.case0x0_13.setWordWrap(False)
        self.case0x0_13.setObjectName(_fromUtf8("case0x0_13"))
        self.case0x0_14 = QtWidgets.QLabel(self.widget)
        self.case0x0_14.setGeometry(QtCore.QRect(120, 340, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.case0x0_14.setFont(font)
        self.case0x0_14.setStyleSheet(_fromUtf8("background-color:#ffffde;"))
        self.case0x0_14.setText(_fromUtf8(""))
        self.case0x0_14.setTextFormat(QtCore.Qt.AutoText)
        self.case0x0_14.setAlignment(QtCore.Qt.AlignCenter)
        self.case0x0_14.setWordWrap(False)
        self.case0x0_14.setObjectName(_fromUtf8("case0x0_14"))
        self.case0x0_15 = QtWidgets.QLabel(self.widget)
        self.case0x0_15.setGeometry(QtCore.QRect(230, 340, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.case0x0_15.setFont(font)
        self.case0x0_15.setStyleSheet(_fromUtf8("background-color:#ffffde;"))
        self.case0x0_15.setText(_fromUtf8(""))
        self.case0x0_15.setTextFormat(QtCore.Qt.AutoText)
        self.case0x0_15.setAlignment(QtCore.Qt.AlignCenter)
        self.case0x0_15.setWordWrap(False)
        self.case0x0_15.setObjectName(_fromUtf8("case0x0_15"))
        self.case0x0_16 = QtWidgets.QLabel(self.widget)
        self.case0x0_16.setGeometry(QtCore.QRect(340, 340, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.case0x0_16.setFont(font)
        self.case0x0_16.setStyleSheet(_fromUtf8("background-color:#ffffde;"))
        self.case0x0_16.setText(_fromUtf8(""))
        self.case0x0_16.setTextFormat(QtCore.Qt.AutoText)
        self.case0x0_16.setAlignment(QtCore.Qt.AlignCenter)
        self.case0x0_16.setWordWrap(False)
        self.case0x0_16.setObjectName(_fromUtf8("case0x0_16"))
        self.score = QtWidgets.QLabel(self.background)
        self.valScore = QtWidgets.QLabel(self.background)
        self.score.setGeometry(QtCore.QRect(10, 70, 71, 21))
        self.valScore.setGeometry(QtCore.QRect(80, 70, 45, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.score.setFont(font)
        self.score.setObjectName(_fromUtf8("score"))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.valScore.setFont(font)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        #self.pushButton = QtWidgets.QPushButton(self.background)
        #self.pushButton.setGeometry(QtCore.QRect(480, 80, 41, 31))
        #self.pushButton.setObjectName(_fromUtf8("pushButton"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.score.setText(_translate("MainWindow", "Score :", None))
        self.valScore.setText(_translate("MainWindow", "0", None))
        #self.pushButton.setText(_translate("MainWindow", "retour", None))

